logging:
  level:
    org:
      springframework:
        security: debug
app:
  jwt-expiration-milliseconds: 86400000
  jwt-secret: jlPSXaNvz1f6gRELt6s64sH2SygfY1TQWNwZbxncSwfwQpezmZdkCcHoCMwCFKKj
spring:
  application:
    name: blogapp
  datasource:
    username: hdurmaz
    url: jdbc:postgresql://localhost:5432/hdurmaz
    password: hdurmaz
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
springdoc:
  swagger-ui:
    operationsSorter: method
    filter: 'false'
    syntaxHighlight:
      activated: 'true'
    enabled: 'true'
    tryItOutEnabled: 'false'
    path: v3/api-docs/swagger-ui.html
